/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const PackageStatus = IDL.Variant({
  'active' : IDL.Null,
  'inactive' : IDL.Null,
});
export const Package = IDL.Record({
  'id' : IDL.Nat,
  'status' : PackageStatus,
  'courses' : IDL.Text,
  'name' : IDL.Text,
  'price' : IDL.Nat,
});
export const AdminStats = IDL.Record({
  'pendingPayments' : IDL.Nat,
  'totalSales' : IDL.Nat,
  'totalUsers' : IDL.Nat,
  'totalRevenue' : IDL.Nat,
});
export const PaymentStatus = IDL.Variant({
  'pending' : IDL.Null,
  'approved' : IDL.Null,
  'rejected' : IDL.Null,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const PaymentProof = IDL.Record({
  'id' : IDL.Nat,
  'status' : PaymentStatus,
  'userId' : IDL.Principal,
  'createdAt' : IDL.Int,
  'packageId' : IDL.Nat,
  'transactionId' : IDL.Text,
  'screenshotBlob' : ExternalBlob,
});
export const Payment = IDL.Record({
  'id' : IDL.Nat,
  'status' : PaymentStatus,
  'userId' : IDL.Principal,
  'createdAt' : IDL.Int,
  'packageId' : IDL.Nat,
  'transactionId' : IDL.Text,
});
export const Role = IDL.Variant({ 'admin' : IDL.Null, 'user' : IDL.Null });
export const UserProfile = IDL.Record({
  'principal' : IDL.Principal,
  'blocked' : IDL.Bool,
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'role' : Role,
  'email' : IDL.Text,
  'phone' : IDL.Text,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'approvePayment' : IDL.Func([IDL.Nat], [], []),
  'approvePaymentProof' : IDL.Func([IDL.Nat], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createPackage' : IDL.Func([IDL.Text, IDL.Nat, IDL.Text], [IDL.Nat], []),
  'createPayment' : IDL.Func([IDL.Nat, IDL.Text], [IDL.Nat], []),
  'deletePackage' : IDL.Func([IDL.Nat], [], []),
  'deleteUser' : IDL.Func([IDL.Principal], [], []),
  'getActivePackages' : IDL.Func([], [IDL.Vec(Package)], ['query']),
  'getAdminStats' : IDL.Func([], [AdminStats], ['query']),
  'getAllPackages' : IDL.Func([], [IDL.Vec(Package)], ['query']),
  'getAllPaymentProofs' : IDL.Func([], [IDL.Vec(PaymentProof)], ['query']),
  'getAllPayments' : IDL.Func([], [IDL.Vec(Payment)], ['query']),
  'getAllUsers' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getMyPaymentProofs' : IDL.Func([], [IDL.Vec(PaymentProof)], ['query']),
  'getMyPayments' : IDL.Func([], [IDL.Vec(Payment)], ['query']),
  'getPaymentProof' : IDL.Func([IDL.Nat], [IDL.Opt(PaymentProof)], ['query']),
  'getPaymentProofsByStatus' : IDL.Func(
      [PaymentStatus],
      [IDL.Vec(PaymentProof)],
      ['query'],
    ),
  'getPaymentsByStatus' : IDL.Func(
      [PaymentStatus],
      [IDL.Vec(Payment)],
      ['query'],
    ),
  'getPaymentsByUser' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(Payment)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'registerUser' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'rejectPayment' : IDL.Func([IDL.Nat], [], []),
  'rejectPaymentProof' : IDL.Func([IDL.Nat], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'submitPaymentProof' : IDL.Func(
      [IDL.Nat, IDL.Text, ExternalBlob],
      [IDL.Nat],
      [],
    ),
  'togglePackageStatus' : IDL.Func([IDL.Nat], [], []),
  'toggleUserBlock' : IDL.Func([IDL.Principal], [], []),
  'updatePackage' : IDL.Func([IDL.Nat, IDL.Text, IDL.Nat, IDL.Text], [], []),
  'updatePaymentProofStatus' : IDL.Func([IDL.Nat, PaymentStatus], [], []),
  'updatePaymentStatus' : IDL.Func([IDL.Nat, PaymentStatus], [], []),
  'updateProfile' : IDL.Func([IDL.Text, IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const PackageStatus = IDL.Variant({
    'active' : IDL.Null,
    'inactive' : IDL.Null,
  });
  const Package = IDL.Record({
    'id' : IDL.Nat,
    'status' : PackageStatus,
    'courses' : IDL.Text,
    'name' : IDL.Text,
    'price' : IDL.Nat,
  });
  const AdminStats = IDL.Record({
    'pendingPayments' : IDL.Nat,
    'totalSales' : IDL.Nat,
    'totalUsers' : IDL.Nat,
    'totalRevenue' : IDL.Nat,
  });
  const PaymentStatus = IDL.Variant({
    'pending' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const PaymentProof = IDL.Record({
    'id' : IDL.Nat,
    'status' : PaymentStatus,
    'userId' : IDL.Principal,
    'createdAt' : IDL.Int,
    'packageId' : IDL.Nat,
    'transactionId' : IDL.Text,
    'screenshotBlob' : ExternalBlob,
  });
  const Payment = IDL.Record({
    'id' : IDL.Nat,
    'status' : PaymentStatus,
    'userId' : IDL.Principal,
    'createdAt' : IDL.Int,
    'packageId' : IDL.Nat,
    'transactionId' : IDL.Text,
  });
  const Role = IDL.Variant({ 'admin' : IDL.Null, 'user' : IDL.Null });
  const UserProfile = IDL.Record({
    'principal' : IDL.Principal,
    'blocked' : IDL.Bool,
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'role' : Role,
    'email' : IDL.Text,
    'phone' : IDL.Text,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'approvePayment' : IDL.Func([IDL.Nat], [], []),
    'approvePaymentProof' : IDL.Func([IDL.Nat], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createPackage' : IDL.Func([IDL.Text, IDL.Nat, IDL.Text], [IDL.Nat], []),
    'createPayment' : IDL.Func([IDL.Nat, IDL.Text], [IDL.Nat], []),
    'deletePackage' : IDL.Func([IDL.Nat], [], []),
    'deleteUser' : IDL.Func([IDL.Principal], [], []),
    'getActivePackages' : IDL.Func([], [IDL.Vec(Package)], ['query']),
    'getAdminStats' : IDL.Func([], [AdminStats], ['query']),
    'getAllPackages' : IDL.Func([], [IDL.Vec(Package)], ['query']),
    'getAllPaymentProofs' : IDL.Func([], [IDL.Vec(PaymentProof)], ['query']),
    'getAllPayments' : IDL.Func([], [IDL.Vec(Payment)], ['query']),
    'getAllUsers' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getMyPaymentProofs' : IDL.Func([], [IDL.Vec(PaymentProof)], ['query']),
    'getMyPayments' : IDL.Func([], [IDL.Vec(Payment)], ['query']),
    'getPaymentProof' : IDL.Func([IDL.Nat], [IDL.Opt(PaymentProof)], ['query']),
    'getPaymentProofsByStatus' : IDL.Func(
        [PaymentStatus],
        [IDL.Vec(PaymentProof)],
        ['query'],
      ),
    'getPaymentsByStatus' : IDL.Func(
        [PaymentStatus],
        [IDL.Vec(Payment)],
        ['query'],
      ),
    'getPaymentsByUser' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(Payment)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'registerUser' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'rejectPayment' : IDL.Func([IDL.Nat], [], []),
    'rejectPaymentProof' : IDL.Func([IDL.Nat], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'submitPaymentProof' : IDL.Func(
        [IDL.Nat, IDL.Text, ExternalBlob],
        [IDL.Nat],
        [],
      ),
    'togglePackageStatus' : IDL.Func([IDL.Nat], [], []),
    'toggleUserBlock' : IDL.Func([IDL.Principal], [], []),
    'updatePackage' : IDL.Func([IDL.Nat, IDL.Text, IDL.Nat, IDL.Text], [], []),
    'updatePaymentProofStatus' : IDL.Func([IDL.Nat, PaymentStatus], [], []),
    'updatePaymentStatus' : IDL.Func([IDL.Nat, PaymentStatus], [], []),
    'updateProfile' : IDL.Func([IDL.Text, IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };