/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AdminStats {
  'pendingPayments' : bigint,
  'totalSales' : bigint,
  'totalUsers' : bigint,
  'totalRevenue' : bigint,
}
export type ExternalBlob = Uint8Array;
export interface Package {
  'id' : bigint,
  'status' : PackageStatus,
  'courses' : string,
  'name' : string,
  'price' : bigint,
}
export type PackageStatus = { 'active' : null } |
  { 'inactive' : null };
export interface Payment {
  'id' : bigint,
  'status' : PaymentStatus,
  'userId' : Principal,
  'createdAt' : bigint,
  'packageId' : bigint,
  'transactionId' : string,
}
export interface PaymentProof {
  'id' : bigint,
  'status' : PaymentStatus,
  'userId' : Principal,
  'createdAt' : bigint,
  'packageId' : bigint,
  'transactionId' : string,
  'screenshotBlob' : ExternalBlob,
}
export type PaymentStatus = { 'pending' : null } |
  { 'approved' : null } |
  { 'rejected' : null };
export type Role = { 'admin' : null } |
  { 'user' : null };
export interface UserProfile {
  'principal' : Principal,
  'blocked' : boolean,
  'name' : string,
  'createdAt' : bigint,
  'role' : Role,
  'email' : string,
  'phone' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'approvePayment' : ActorMethod<[bigint], undefined>,
  'approvePaymentProof' : ActorMethod<[bigint], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createPackage' : ActorMethod<[string, bigint, string], bigint>,
  'createPayment' : ActorMethod<[bigint, string], bigint>,
  'deletePackage' : ActorMethod<[bigint], undefined>,
  'deleteUser' : ActorMethod<[Principal], undefined>,
  'getActivePackages' : ActorMethod<[], Array<Package>>,
  'getAdminStats' : ActorMethod<[], AdminStats>,
  'getAllPackages' : ActorMethod<[], Array<Package>>,
  'getAllPaymentProofs' : ActorMethod<[], Array<PaymentProof>>,
  'getAllPayments' : ActorMethod<[], Array<Payment>>,
  'getAllUsers' : ActorMethod<[], Array<UserProfile>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getMyPaymentProofs' : ActorMethod<[], Array<PaymentProof>>,
  'getMyPayments' : ActorMethod<[], Array<Payment>>,
  'getPaymentProof' : ActorMethod<[bigint], [] | [PaymentProof]>,
  'getPaymentProofsByStatus' : ActorMethod<
    [PaymentStatus],
    Array<PaymentProof>
  >,
  'getPaymentsByStatus' : ActorMethod<[PaymentStatus], Array<Payment>>,
  'getPaymentsByUser' : ActorMethod<[Principal], Array<Payment>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'registerUser' : ActorMethod<[string, string, string], undefined>,
  'rejectPayment' : ActorMethod<[bigint], undefined>,
  'rejectPaymentProof' : ActorMethod<[bigint], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'submitPaymentProof' : ActorMethod<[bigint, string, ExternalBlob], bigint>,
  'togglePackageStatus' : ActorMethod<[bigint], undefined>,
  'toggleUserBlock' : ActorMethod<[Principal], undefined>,
  'updatePackage' : ActorMethod<[bigint, string, bigint, string], undefined>,
  'updatePaymentProofStatus' : ActorMethod<[bigint, PaymentStatus], undefined>,
  'updatePaymentStatus' : ActorMethod<[bigint, PaymentStatus], undefined>,
  'updateProfile' : ActorMethod<[string, string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];