/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ShoppingItem = IDL.Record({
  'productName' : IDL.Text,
  'currency' : IDL.Text,
  'quantity' : IDL.Nat,
  'priceInCents' : IDL.Nat,
  'productDescription' : IDL.Text,
});
export const CouponDiscountType = IDL.Variant({
  'fixed' : IDL.Null,
  'percent' : IDL.Null,
});
export const CouponCode = IDL.Record({
  'id' : IDL.Nat,
  'active' : IDL.Bool,
  'discountValue' : IDL.Nat,
  'code' : IDL.Text,
  'createdAt' : IDL.Int,
  'discountType' : CouponDiscountType,
});
export const PackageStatus = IDL.Variant({
  'active' : IDL.Null,
  'inactive' : IDL.Null,
});
export const Package = IDL.Record({
  'id' : IDL.Nat,
  'status' : PackageStatus,
  'courses' : IDL.Text,
  'name' : IDL.Text,
  'price' : IDL.Nat,
});
export const AdminStats = IDL.Record({
  'pendingPayments' : IDL.Nat,
  'totalSales' : IDL.Nat,
  'totalUsers' : IDL.Nat,
  'totalRevenue' : IDL.Nat,
});
export const ContactInterest = IDL.Record({
  'id' : IDL.Nat,
  'resolved' : IDL.Bool,
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'email' : IDL.Text,
  'message' : IDL.Text,
  'phone' : IDL.Text,
});
export const PaymentStatus = IDL.Variant({
  'pending' : IDL.Null,
  'approved' : IDL.Null,
  'rejected' : IDL.Null,
});
export const PaymentProof = IDL.Record({
  'id' : IDL.Nat,
  'status' : PaymentStatus,
  'userId' : IDL.Principal,
  'createdAt' : IDL.Int,
  'packageId' : IDL.Nat,
  'transactionId' : IDL.Text,
  'screenshotBlob' : ExternalBlob,
});
export const Payment = IDL.Record({
  'id' : IDL.Nat,
  'status' : PaymentStatus,
  'userId' : IDL.Principal,
  'createdAt' : IDL.Int,
  'packageId' : IDL.Nat,
  'transactionId' : IDL.Text,
});
export const ServiceContent = IDL.Record({
  'title' : IDL.Text,
  'features' : IDL.Vec(IDL.Text),
  'originalPrice' : IDL.Nat,
  'deliveryDays' : IDL.Text,
  'description' : IDL.Text,
  'isActive' : IDL.Bool,
  'imageUrl' : IDL.Text,
  'serviceId' : IDL.Text,
  'price' : IDL.Nat,
  'videoUrl' : IDL.Text,
});
export const ServiceImage = IDL.Record({
  'id' : IDL.Nat,
  'serviceCategory' : IDL.Text,
  'imageBlob' : ExternalBlob,
  'createdAt' : IDL.Int,
});
export const OrderStatus = IDL.Variant({
  'cancelled' : IDL.Null,
  'pending' : IDL.Null,
  'completed' : IDL.Null,
  'inProgress' : IDL.Null,
});
export const ServiceOrder = IDL.Record({
  'id' : IDL.Nat,
  'status' : OrderStatus,
  'userName' : IDL.Text,
  'serviceName' : IDL.Text,
  'userEmail' : IDL.Text,
  'userId' : IDL.Principal,
  'createdAt' : IDL.Int,
  'price' : IDL.Nat,
  'planName' : IDL.Text,
});
export const Role = IDL.Variant({ 'admin' : IDL.Null, 'user' : IDL.Null });
export const UserProfile = IDL.Record({
  'principal' : IDL.Principal,
  'blocked' : IDL.Bool,
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'role' : Role,
  'email' : IDL.Text,
  'profilePhotoUrl' : IDL.Opt(IDL.Text),
  'phone' : IDL.Text,
});
export const WithdrawalRequestStatus = IDL.Variant({
  'pending' : IDL.Null,
  'approved' : IDL.Null,
  'rejected' : IDL.Null,
});
export const WithdrawalRequest = IDL.Record({
  'id' : IDL.Nat,
  'status' : WithdrawalRequestStatus,
  'userId' : IDL.Principal,
  'createdAt' : IDL.Int,
  'message' : IDL.Text,
  'amount' : IDL.Nat,
});
export const Earnings = IDL.Record({
  'today' : IDL.Nat,
  'lifetime' : IDL.Nat,
  'monthly' : IDL.Nat,
  'weekly' : IDL.Nat,
});
export const LandingPage = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'content' : IDL.Text,
  'visitCount' : IDL.Nat,
  'userId' : IDL.Principal,
  'createdAt' : IDL.Int,
  'updatedAt' : IDL.Int,
  'template' : IDL.Text,
});
export const BankDetails = IDL.Record({
  'branch' : IDL.Text,
  'qrCodeBlob' : ExternalBlob,
  'ifsc' : IDL.Text,
  'accountHolderName' : IDL.Text,
  'upiHandle' : IDL.Text,
  'accountNumber' : IDL.Text,
});
export const PhonePeDetails = IDL.Record({
  'qrCodeBlob' : ExternalBlob,
  'upiId' : IDL.Text,
});
export const SiteContent = IDL.Record({
  'bankDetails' : BankDetails,
  'phonePeDetails' : PhonePeDetails,
  'whatsappPhoneNumber' : IDL.Text,
});
export const ReferralStatus = IDL.Variant({
  'pending' : IDL.Null,
  'paid' : IDL.Null,
  'approved' : IDL.Null,
});
export const CommissionType = IDL.Variant({
  'active' : IDL.Null,
  'passive' : IDL.Null,
});
export const Referral = IDL.Record({
  'id' : IDL.Nat,
  'status' : ReferralStatus,
  'referredUserId' : IDL.Principal,
  'createdAt' : IDL.Int,
  'referrerId' : IDL.Principal,
  'commissionAmount' : IDL.Nat,
  'commissionType' : CommissionType,
  'packageId' : IDL.Nat,
});
export const StripeSessionStatus = IDL.Variant({
  'completed' : IDL.Record({
    'userPrincipal' : IDL.Opt(IDL.Text),
    'response' : IDL.Text,
  }),
  'failed' : IDL.Record({ 'error' : IDL.Text }),
});
export const StripeConfiguration = IDL.Record({
  'allowedCountries' : IDL.Vec(IDL.Text),
  'secretKey' : IDL.Text,
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addServiceImage' : IDL.Func([IDL.Text, ExternalBlob], [IDL.Nat], []),
  'approvePayment' : IDL.Func([IDL.Nat], [], []),
  'approvePaymentProof' : IDL.Func([IDL.Nat], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'assignPlatinumPackageByEmail' : IDL.Func([IDL.Text], [], []),
  'createCheckoutSession' : IDL.Func(
      [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
      [IDL.Text],
      [],
    ),
  'createCoupon' : IDL.Func(
      [IDL.Text, CouponDiscountType, IDL.Nat],
      [IDL.Nat],
      [],
    ),
  'createLandingPage' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [IDL.Nat], []),
  'createPackage' : IDL.Func([IDL.Text, IDL.Nat, IDL.Text], [IDL.Nat], []),
  'createPayment' : IDL.Func([IDL.Nat, IDL.Text], [IDL.Nat], []),
  'createWithdrawalRequest' : IDL.Func([IDL.Nat, IDL.Text], [IDL.Nat], []),
  'deleteCoupon' : IDL.Func([IDL.Nat], [], []),
  'deleteLandingPage' : IDL.Func([IDL.Nat], [], []),
  'deletePackage' : IDL.Func([IDL.Nat], [], []),
  'deleteServiceImage' : IDL.Func([IDL.Nat], [], []),
  'deleteUser' : IDL.Func([IDL.Principal], [], []),
  'getActiveCoupons' : IDL.Func([], [IDL.Vec(CouponCode)], ['query']),
  'getActivePackages' : IDL.Func([], [IDL.Vec(Package)], ['query']),
  'getAdminStats' : IDL.Func([], [AdminStats], ['query']),
  'getAllContactInterests' : IDL.Func(
      [],
      [IDL.Vec(ContactInterest)],
      ['query'],
    ),
  'getAllCoupons' : IDL.Func([], [IDL.Vec(CouponCode)], ['query']),
  'getAllPackages' : IDL.Func([], [IDL.Vec(Package)], ['query']),
  'getAllPaymentProofs' : IDL.Func([], [IDL.Vec(PaymentProof)], ['query']),
  'getAllPayments' : IDL.Func([], [IDL.Vec(Payment)], ['query']),
  'getAllServiceContents' : IDL.Func([], [IDL.Vec(ServiceContent)], ['query']),
  'getAllServiceImages' : IDL.Func([], [IDL.Vec(ServiceImage)], ['query']),
  'getAllServiceOrders' : IDL.Func([], [IDL.Vec(ServiceOrder)], ['query']),
  'getAllUsers' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
  'getAllWithdrawalRequests' : IDL.Func(
      [],
      [IDL.Vec(WithdrawalRequest)],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getEarnings' : IDL.Func([IDL.Principal], [Earnings], ['query']),
  'getLandingPage' : IDL.Func([IDL.Nat], [IDL.Opt(LandingPage)], ['query']),
  'getLandingPageById' : IDL.Func([IDL.Nat], [IDL.Opt(LandingPage)], ['query']),
  'getLandingPages' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(LandingPage)],
      ['query'],
    ),
  'getMyPaymentProofs' : IDL.Func([], [IDL.Vec(PaymentProof)], ['query']),
  'getMyPayments' : IDL.Func([], [IDL.Vec(Payment)], ['query']),
  'getMyServiceOrders' : IDL.Func([], [IDL.Vec(ServiceOrder)], ['query']),
  'getPaymentProof' : IDL.Func([IDL.Nat], [IDL.Opt(PaymentProof)], ['query']),
  'getPaymentProofsByStatus' : IDL.Func(
      [PaymentStatus],
      [IDL.Vec(PaymentProof)],
      ['query'],
    ),
  'getPaymentsByStatus' : IDL.Func(
      [PaymentStatus],
      [IDL.Vec(Payment)],
      ['query'],
    ),
  'getPaymentsByUser' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(Payment)],
      ['query'],
    ),
  'getPersistentSiteContent' : IDL.Func([], [IDL.Opt(SiteContent)], ['query']),
  'getReferralsByUser' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(Referral)],
      ['query'],
    ),
  'getServiceContent' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(ServiceContent)],
      ['query'],
    ),
  'getServiceImages' : IDL.Func([IDL.Text], [IDL.Vec(ServiceImage)], ['query']),
  'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
  'getTotalCommissions' : IDL.Func(
      [IDL.Principal],
      [
        IDL.Record({
          'totalPassive' : IDL.Nat,
          'pending' : IDL.Nat,
          'totalActive' : IDL.Nat,
        }),
      ],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getWithdrawalRequests' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(WithdrawalRequest)],
      ['query'],
    ),
  'incrementLandingPageVisit' : IDL.Func([IDL.Nat], [], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
  'markContactResolved' : IDL.Func([IDL.Nat], [], []),
  'recordPurchase' : IDL.Func([IDL.Principal, IDL.Nat], [], []),
  'registerUser' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Opt(IDL.Principal)],
      [],
      [],
    ),
  'rejectPayment' : IDL.Func([IDL.Nat], [], []),
  'rejectPaymentProof' : IDL.Func([IDL.Nat], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'saveServiceOrder' : IDL.Func([IDL.Text, IDL.Text, IDL.Nat], [IDL.Nat], []),
  'setPersistentSiteContent' : IDL.Func([SiteContent], [], []),
  'setServiceContent' : IDL.Func([ServiceContent], [], []),
  'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
  'submitContactInterest' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'submitPaymentProof' : IDL.Func(
      [IDL.Nat, IDL.Text, ExternalBlob],
      [IDL.Nat],
      [],
    ),
  'toggleCouponActive' : IDL.Func([IDL.Nat], [], []),
  'togglePackageStatus' : IDL.Func([IDL.Nat], [], []),
  'toggleUserBlock' : IDL.Func([IDL.Principal], [], []),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'updateCoupon' : IDL.Func(
      [IDL.Nat, IDL.Text, CouponDiscountType, IDL.Nat],
      [],
      [],
    ),
  'updateLandingPage' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text], [], []),
  'updatePackage' : IDL.Func([IDL.Nat, IDL.Text, IDL.Nat, IDL.Text], [], []),
  'updatePaymentProofStatus' : IDL.Func([IDL.Nat, PaymentStatus], [], []),
  'updatePaymentStatus' : IDL.Func([IDL.Nat, PaymentStatus], [], []),
  'updateProfile' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'updateRequestStatus' : IDL.Func([IDL.Nat, WithdrawalRequestStatus], [], []),
  'updateServiceOrderStatus' : IDL.Func([IDL.Nat, OrderStatus], [], []),
  'uploadProfilePhoto' : IDL.Func([ExternalBlob], [IDL.Text], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ShoppingItem = IDL.Record({
    'productName' : IDL.Text,
    'currency' : IDL.Text,
    'quantity' : IDL.Nat,
    'priceInCents' : IDL.Nat,
    'productDescription' : IDL.Text,
  });
  const CouponDiscountType = IDL.Variant({
    'fixed' : IDL.Null,
    'percent' : IDL.Null,
  });
  const CouponCode = IDL.Record({
    'id' : IDL.Nat,
    'active' : IDL.Bool,
    'discountValue' : IDL.Nat,
    'code' : IDL.Text,
    'createdAt' : IDL.Int,
    'discountType' : CouponDiscountType,
  });
  const PackageStatus = IDL.Variant({
    'active' : IDL.Null,
    'inactive' : IDL.Null,
  });
  const Package = IDL.Record({
    'id' : IDL.Nat,
    'status' : PackageStatus,
    'courses' : IDL.Text,
    'name' : IDL.Text,
    'price' : IDL.Nat,
  });
  const AdminStats = IDL.Record({
    'pendingPayments' : IDL.Nat,
    'totalSales' : IDL.Nat,
    'totalUsers' : IDL.Nat,
    'totalRevenue' : IDL.Nat,
  });
  const ContactInterest = IDL.Record({
    'id' : IDL.Nat,
    'resolved' : IDL.Bool,
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'email' : IDL.Text,
    'message' : IDL.Text,
    'phone' : IDL.Text,
  });
  const PaymentStatus = IDL.Variant({
    'pending' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
  });
  const PaymentProof = IDL.Record({
    'id' : IDL.Nat,
    'status' : PaymentStatus,
    'userId' : IDL.Principal,
    'createdAt' : IDL.Int,
    'packageId' : IDL.Nat,
    'transactionId' : IDL.Text,
    'screenshotBlob' : ExternalBlob,
  });
  const Payment = IDL.Record({
    'id' : IDL.Nat,
    'status' : PaymentStatus,
    'userId' : IDL.Principal,
    'createdAt' : IDL.Int,
    'packageId' : IDL.Nat,
    'transactionId' : IDL.Text,
  });
  const ServiceContent = IDL.Record({
    'title' : IDL.Text,
    'features' : IDL.Vec(IDL.Text),
    'originalPrice' : IDL.Nat,
    'deliveryDays' : IDL.Text,
    'description' : IDL.Text,
    'isActive' : IDL.Bool,
    'imageUrl' : IDL.Text,
    'serviceId' : IDL.Text,
    'price' : IDL.Nat,
    'videoUrl' : IDL.Text,
  });
  const ServiceImage = IDL.Record({
    'id' : IDL.Nat,
    'serviceCategory' : IDL.Text,
    'imageBlob' : ExternalBlob,
    'createdAt' : IDL.Int,
  });
  const OrderStatus = IDL.Variant({
    'cancelled' : IDL.Null,
    'pending' : IDL.Null,
    'completed' : IDL.Null,
    'inProgress' : IDL.Null,
  });
  const ServiceOrder = IDL.Record({
    'id' : IDL.Nat,
    'status' : OrderStatus,
    'userName' : IDL.Text,
    'serviceName' : IDL.Text,
    'userEmail' : IDL.Text,
    'userId' : IDL.Principal,
    'createdAt' : IDL.Int,
    'price' : IDL.Nat,
    'planName' : IDL.Text,
  });
  const Role = IDL.Variant({ 'admin' : IDL.Null, 'user' : IDL.Null });
  const UserProfile = IDL.Record({
    'principal' : IDL.Principal,
    'blocked' : IDL.Bool,
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'role' : Role,
    'email' : IDL.Text,
    'profilePhotoUrl' : IDL.Opt(IDL.Text),
    'phone' : IDL.Text,
  });
  const WithdrawalRequestStatus = IDL.Variant({
    'pending' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
  });
  const WithdrawalRequest = IDL.Record({
    'id' : IDL.Nat,
    'status' : WithdrawalRequestStatus,
    'userId' : IDL.Principal,
    'createdAt' : IDL.Int,
    'message' : IDL.Text,
    'amount' : IDL.Nat,
  });
  const Earnings = IDL.Record({
    'today' : IDL.Nat,
    'lifetime' : IDL.Nat,
    'monthly' : IDL.Nat,
    'weekly' : IDL.Nat,
  });
  const LandingPage = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'content' : IDL.Text,
    'visitCount' : IDL.Nat,
    'userId' : IDL.Principal,
    'createdAt' : IDL.Int,
    'updatedAt' : IDL.Int,
    'template' : IDL.Text,
  });
  const BankDetails = IDL.Record({
    'branch' : IDL.Text,
    'qrCodeBlob' : ExternalBlob,
    'ifsc' : IDL.Text,
    'accountHolderName' : IDL.Text,
    'upiHandle' : IDL.Text,
    'accountNumber' : IDL.Text,
  });
  const PhonePeDetails = IDL.Record({
    'qrCodeBlob' : ExternalBlob,
    'upiId' : IDL.Text,
  });
  const SiteContent = IDL.Record({
    'bankDetails' : BankDetails,
    'phonePeDetails' : PhonePeDetails,
    'whatsappPhoneNumber' : IDL.Text,
  });
  const ReferralStatus = IDL.Variant({
    'pending' : IDL.Null,
    'paid' : IDL.Null,
    'approved' : IDL.Null,
  });
  const CommissionType = IDL.Variant({
    'active' : IDL.Null,
    'passive' : IDL.Null,
  });
  const Referral = IDL.Record({
    'id' : IDL.Nat,
    'status' : ReferralStatus,
    'referredUserId' : IDL.Principal,
    'createdAt' : IDL.Int,
    'referrerId' : IDL.Principal,
    'commissionAmount' : IDL.Nat,
    'commissionType' : CommissionType,
    'packageId' : IDL.Nat,
  });
  const StripeSessionStatus = IDL.Variant({
    'completed' : IDL.Record({
      'userPrincipal' : IDL.Opt(IDL.Text),
      'response' : IDL.Text,
    }),
    'failed' : IDL.Record({ 'error' : IDL.Text }),
  });
  const StripeConfiguration = IDL.Record({
    'allowedCountries' : IDL.Vec(IDL.Text),
    'secretKey' : IDL.Text,
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addServiceImage' : IDL.Func([IDL.Text, ExternalBlob], [IDL.Nat], []),
    'approvePayment' : IDL.Func([IDL.Nat], [], []),
    'approvePaymentProof' : IDL.Func([IDL.Nat], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'assignPlatinumPackageByEmail' : IDL.Func([IDL.Text], [], []),
    'createCheckoutSession' : IDL.Func(
        [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
        [IDL.Text],
        [],
      ),
    'createCoupon' : IDL.Func(
        [IDL.Text, CouponDiscountType, IDL.Nat],
        [IDL.Nat],
        [],
      ),
    'createLandingPage' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'createPackage' : IDL.Func([IDL.Text, IDL.Nat, IDL.Text], [IDL.Nat], []),
    'createPayment' : IDL.Func([IDL.Nat, IDL.Text], [IDL.Nat], []),
    'createWithdrawalRequest' : IDL.Func([IDL.Nat, IDL.Text], [IDL.Nat], []),
    'deleteCoupon' : IDL.Func([IDL.Nat], [], []),
    'deleteLandingPage' : IDL.Func([IDL.Nat], [], []),
    'deletePackage' : IDL.Func([IDL.Nat], [], []),
    'deleteServiceImage' : IDL.Func([IDL.Nat], [], []),
    'deleteUser' : IDL.Func([IDL.Principal], [], []),
    'getActiveCoupons' : IDL.Func([], [IDL.Vec(CouponCode)], ['query']),
    'getActivePackages' : IDL.Func([], [IDL.Vec(Package)], ['query']),
    'getAdminStats' : IDL.Func([], [AdminStats], ['query']),
    'getAllContactInterests' : IDL.Func(
        [],
        [IDL.Vec(ContactInterest)],
        ['query'],
      ),
    'getAllCoupons' : IDL.Func([], [IDL.Vec(CouponCode)], ['query']),
    'getAllPackages' : IDL.Func([], [IDL.Vec(Package)], ['query']),
    'getAllPaymentProofs' : IDL.Func([], [IDL.Vec(PaymentProof)], ['query']),
    'getAllPayments' : IDL.Func([], [IDL.Vec(Payment)], ['query']),
    'getAllServiceContents' : IDL.Func(
        [],
        [IDL.Vec(ServiceContent)],
        ['query'],
      ),
    'getAllServiceImages' : IDL.Func([], [IDL.Vec(ServiceImage)], ['query']),
    'getAllServiceOrders' : IDL.Func([], [IDL.Vec(ServiceOrder)], ['query']),
    'getAllUsers' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
    'getAllWithdrawalRequests' : IDL.Func(
        [],
        [IDL.Vec(WithdrawalRequest)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getEarnings' : IDL.Func([IDL.Principal], [Earnings], ['query']),
    'getLandingPage' : IDL.Func([IDL.Nat], [IDL.Opt(LandingPage)], ['query']),
    'getLandingPageById' : IDL.Func(
        [IDL.Nat],
        [IDL.Opt(LandingPage)],
        ['query'],
      ),
    'getLandingPages' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(LandingPage)],
        ['query'],
      ),
    'getMyPaymentProofs' : IDL.Func([], [IDL.Vec(PaymentProof)], ['query']),
    'getMyPayments' : IDL.Func([], [IDL.Vec(Payment)], ['query']),
    'getMyServiceOrders' : IDL.Func([], [IDL.Vec(ServiceOrder)], ['query']),
    'getPaymentProof' : IDL.Func([IDL.Nat], [IDL.Opt(PaymentProof)], ['query']),
    'getPaymentProofsByStatus' : IDL.Func(
        [PaymentStatus],
        [IDL.Vec(PaymentProof)],
        ['query'],
      ),
    'getPaymentsByStatus' : IDL.Func(
        [PaymentStatus],
        [IDL.Vec(Payment)],
        ['query'],
      ),
    'getPaymentsByUser' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(Payment)],
        ['query'],
      ),
    'getPersistentSiteContent' : IDL.Func(
        [],
        [IDL.Opt(SiteContent)],
        ['query'],
      ),
    'getReferralsByUser' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(Referral)],
        ['query'],
      ),
    'getServiceContent' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(ServiceContent)],
        ['query'],
      ),
    'getServiceImages' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(ServiceImage)],
        ['query'],
      ),
    'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
    'getTotalCommissions' : IDL.Func(
        [IDL.Principal],
        [
          IDL.Record({
            'totalPassive' : IDL.Nat,
            'pending' : IDL.Nat,
            'totalActive' : IDL.Nat,
          }),
        ],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getWithdrawalRequests' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(WithdrawalRequest)],
        ['query'],
      ),
    'incrementLandingPageVisit' : IDL.Func([IDL.Nat], [], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
    'markContactResolved' : IDL.Func([IDL.Nat], [], []),
    'recordPurchase' : IDL.Func([IDL.Principal, IDL.Nat], [], []),
    'registerUser' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Opt(IDL.Principal)],
        [],
        [],
      ),
    'rejectPayment' : IDL.Func([IDL.Nat], [], []),
    'rejectPaymentProof' : IDL.Func([IDL.Nat], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'saveServiceOrder' : IDL.Func([IDL.Text, IDL.Text, IDL.Nat], [IDL.Nat], []),
    'setPersistentSiteContent' : IDL.Func([SiteContent], [], []),
    'setServiceContent' : IDL.Func([ServiceContent], [], []),
    'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
    'submitContactInterest' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'submitPaymentProof' : IDL.Func(
        [IDL.Nat, IDL.Text, ExternalBlob],
        [IDL.Nat],
        [],
      ),
    'toggleCouponActive' : IDL.Func([IDL.Nat], [], []),
    'togglePackageStatus' : IDL.Func([IDL.Nat], [], []),
    'toggleUserBlock' : IDL.Func([IDL.Principal], [], []),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'updateCoupon' : IDL.Func(
        [IDL.Nat, IDL.Text, CouponDiscountType, IDL.Nat],
        [],
        [],
      ),
    'updateLandingPage' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text], [], []),
    'updatePackage' : IDL.Func([IDL.Nat, IDL.Text, IDL.Nat, IDL.Text], [], []),
    'updatePaymentProofStatus' : IDL.Func([IDL.Nat, PaymentStatus], [], []),
    'updatePaymentStatus' : IDL.Func([IDL.Nat, PaymentStatus], [], []),
    'updateProfile' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'updateRequestStatus' : IDL.Func(
        [IDL.Nat, WithdrawalRequestStatus],
        [],
        [],
      ),
    'updateServiceOrderStatus' : IDL.Func([IDL.Nat, OrderStatus], [], []),
    'uploadProfilePhoto' : IDL.Func([ExternalBlob], [IDL.Text], []),
  });
};

export const init = ({ IDL }) => { return []; };